1st version of an AnnounceLogic. It is used to broadcast audio messag…
sm0svx/svxlink pull request #586
Opened 2022-06-16 05:49 UTC by dl1hrc

…es "Rundsprueche" at predefined time/dates to connected logics or repeater systems.

Maybe could be interesting?
mni 73s de Adi / DL1HRC

2022-09-04 15:55 UTC, Dloranger commented
@dl1hrc 

I have been working on a similar system but mine is all TCL so no need to compile anything. Not saying mine is better by any means, just a different approach. We should compare notes and merge approaches into a single setup so we are not doing redundant work

2022-09-04 16:44 UTC, dl1hrc commented
ok Daniel, my approach was to have a stupid core logic that provide a simple functionality for streaming announcements into a reflector linked network, normally known as broadcasts.
Some ideas what an AnnounceLogic should do (in my opinion):

- linking it with all reflectors that are available on a local node by command (dtmf, pty ...)
- time/date controlled playback of announcements
- sending out announcements e.g. once a year/month/week/day/hour/minute due to configuration
- sending greetings (Whitsun, Easter, ...)
- dynamic playback of announcements "on-the-fly"
- no influence to the linked logics (rx/tx) out of playing back announcements

It's  just an idea, it should be very flexible, e.g. if you have 4 links it should be no problem to link a single AnnounceLogic as well as to have 4 different AnnounceLogics. Maybe I have to work on it to fulfill this requirement.

Mni 73s de Adi / DL1HRC

2022-09-04 17:31 UTC, Dloranger commented
Here are my so far very simple working scripts, not ready for error handling, polite announcing, etc yet, but should show the basic approach for the arrays
[annoucements.zip](https://github.com/sm0svx/svxlink/files/9485171/annoucements.zip)

2022-09-04 18:45 UTC, dl1hrc commented
ok, the question is does it send it into the network or does it announce it only at the local node? My idea was to send the information to all connected nodes from time to time.

2022-10-11 06:54 UTC, Dloranger commented
My scripts are setup to use a simple array of data (needs expanded for
month and year still, with start and stop conditions, etc)

So far the data array looks like this

Day of week (wildcard or 0-6)
Hour of day (wildcard or specific 24 hour)
Minute (0-59)
.wav path to announcement to play (assumption is you will have a single
file rather than stitching together a bunch of words)

So its something like this

#D  H  M Path
* * 10 /path/to/announcement.wav

This will then play the announcement every day, every hour at the 10 minute
marker.

At the 1 min timer, the script itterates thru the list and plays any
announcements that are due using the existing functions (playsound? Need to
review)

I will dig up some files to share so you can take a look at the approach I
am using

Dan


On Sun, Sep 4, 2022, 9:44 AM Adi Bier ***@***.***> wrote:

> ok Daniel, my approach was to have a stupid core logic that provide a
> simple functionality for streaming announcements into a reflector linked
> network, normally known as broadcasts.
> Some ideas what an AnnounceLogic should do (in my opinion):
>
>    - linking it with all reflectors that are available on a local node by
>    command (dtmf, pty ...)
>    - time/date controlled playback of announcements
>    - sending out announcements e.g. once a
>    year/month/week/day/hour/minute due to configuration
>    - sending greetings (Whitsun, Easter, ...)
>    - dynamic playback of announcements "on-the-fly"
>    - no influence to the linked logics (rx/tx) out of playing back
>    announcements
>
> It's just an idea, it should be very flexible, e.g. if you have 4 links it
> should be no problem to link a single AnnounceLogic as well as to have 4
> different AnnounceLogics. Maybe I have to work on it to fulfill this
> requirement.
>
> Mni 73s de Adi / DL1HRC
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sm0svx/svxlink/pull/586#issuecomment-1236377217>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACPI3DJNQXKC6QLGL53EUNTV4TGXZANCNFSM5Y5SYNEQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-07-20 15:42 UTC, sm0svx requested changes
If you make the changes I have requested in this review I think it will be a quick and simple process to merge this PR.

2023-07-20 15:42 UTC, sm0svx commented on src/CMakeLists.txt
Why have you added -fPIC to the compiler flags?

2023-07-20 15:42 UTC, sm0svx commented on src/doc/man/svxlink.conf.5
I guess you can remove these changes since you have a complete manual page in your contrib directory.

2023-07-20 15:42 UTC, sm0svx commented on src/svxlink/svxlink/Logic.cpp
Just whitespace changes. Please remove.

2023-07-20 15:42 UTC, sm0svx commented on src/svxlink/svxlink/ReflectorLogic.h
These changes does not seem to be connected to the AnnounceLogic.

2023-07-20 15:42 UTC, sm0svx commented on src/svxlink/svxlink/svxlink.cpp
Only whitespace changes. Please revert to original.

2023-07-20 18:57 UTC, dl1hrc commented on src/CMakeLists.txt
when using together with sip compiling can fail under some circumstances (hardware specific). The compiler gives out the hint to compile the framework with -fPIC option. For this extension I think it's not interesting, so I removed it.

2023-07-20 19:03 UTC, dl1hrc commented
ok, just checked in the changes according to your hints. Thank you!
Mni 73s de Adi / DL1HRC

2023-07-20 21:19 UTC, sm0svx commented on src/CMakeLists.txt
The -fPIC switch should normally only be required when building shared libraries or any dynamically loaded object, like plugins. CMake should automatically add that switch where needed. Compiling all code using PIC make no sense and may have a small performance impact so it should not be added in the top-level CMakeLists.txt but rather exactly where it is needed.

2023-07-20 21:22 UTC, sm0svx approved these changes

2023-07-20 21:29 UTC, merged

2023-07-21 04:53 UTC, sp2ong commented
Adi,

I suggest adding README.adoc which will contain short info about AnnounceLogic and how to compile like

..... -DWITH_CONTRIB_AnnounceLogic=ON

it will be useful who will try to use

and maybe link to your PDF document (in Germany language) where is more info about this

73 Waldek

2023-07-21 05:09 UTC, sp2ong commented
Adi,

It will be useful to add info that we need to create in the sounds directory AnnounceLogic/ which contains the file prenotification.wav 
Can you write what this file contains?

2023-07-21 05:14 UTC, sp2ong commented
I see in AnnounceLogic.tcl that this Logic use sounds wav files "prenotify.wav". "Broadcast.wav" do you have example?

2023-07-21 05:31 UTC, sp2ong commented
Adi,

Please check the files:

https://github.com/sm0svx/svxlink/blob/master/src/svxlink/svxlink/contrib/AnnounceLogic/AnnounceLogic.conf.5
and
https://github.com/sm0svx/svxlink/blob/master/src/svxlink/svxlink/contrib/AnnounceLogic/AnnounceLogic.conf.in

different parameters contains it looks like AnnounceLogic.conf.5 is not from this branch ??? maybe I do not understand the full AnnounceLogic ?

2023-07-21 06:20 UTC, sp2ong commented
Adi,

I suggest a change in this file
https://github.com/sm0svx/svxlink/blob/master/src/svxlink/svxlink/contrib/AnnounceLogic/AnnounceLogic.conf.in

**[Announce]**

to

**[AnnounceLogic]**

it will be compatible with name of tcl file

https://github.com/sm0svx/svxlink/blob/master/src/svxlink/svxlink/contrib/AnnounceLogic/AnnounceLogic.tcl

_namespace eval AnnounceLogic {_

or I am wrong 

73 Waldek

2023-07-21 07:12 UTC, dl1hrc commented
Hi Waldek, thank you for the hints, will check it soon. Mni 73s de Adi / DL1HRC